#!/bin/bash

echo "Setting up tunnel for TradingView webhooks..."
echo ""
echo "Option 1: ngrok (recommended for testing)"
echo "==========================================="
echo "1. Install ngrok:"
echo "   brew install ngrok/ngrok/ngrok"
echo ""
echo "2. Start tunnel:"
echo "   ngrok http 3000"
echo ""
echo "3. Use the HTTPS URL provided by ngrok in TradingView alerts"
echo ""

echo "Option 2: Cloudflare Tunnel (for production)"
echo "============================================="
echo "1. Install cloudflared:"
echo "   brew install cloudflared"
echo ""
echo "2. Login to Cloudflare:"
echo "   cloudflared tunnel login"
echo ""
echo "3. Create tunnel:"
echo "   cloudflared tunnel create enclave-bot"
echo ""
echo "4. Create config file ~/.cloudflared/config.yml:"
echo "   tunnel: <TUNNEL_ID>"
echo "   credentials-file: /Users/$USER/.cloudflared/<TUNNEL_ID>.json"
echo "   ingress:"
echo "     - hostname: bot.yourdomain.com"
echo "       service: http://localhost:3000"
echo "     - service: http_status:404"
echo ""
echo "5. Route traffic:"
echo "   cloudflared tunnel route dns enclave-bot bot.yourdomain.com"
echo ""
echo "6. Run tunnel:"
echo "   cloudflared tunnel run enclave-bot"
echo ""

echo "Option 3: localtunnel (quick alternative)"
echo "========================================="
echo "1. Install localtunnel:"
echo "   npm install -g localtunnel"
echo ""
echo "2. Start tunnel:"
echo "   lt --port 3000 --subdomain enclave-bot"
echo ""

echo "Testing the webhook locally:"
echo "============================="
echo "curl -X POST http://localhost:3000/webhook/tradingview \\"
echo '  -H "Content-Type: application/json" \'
echo '  -d '"'"'{"ticker":"BTCUSDT","action":"buy","price":"115000","strategy":"breakout"}'"'"
echo ""
echo "Manual trigger:"
echo "curl -X POST http://localhost:3000/trigger/BTC-USD.P/buy"